"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-08-04 04:33:47.314973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

import db.base

# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidates',
    sa.Column('id', db.base.GUID(), nullable=False),
    sa.Column('display_identifier', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jobs',
    sa.Column('id', db.base.GUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('raw_description', sa.Text(), nullable=False),
    sa.Column('minimum_relevant_years', sa.Numeric(precision=6, scale=2, asdecimal=False), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.Column('parser_version', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('candidate_qualifications',
    sa.Column('id', db.base.GUID(), nullable=False),
    sa.Column('candidate_id', db.base.GUID(), nullable=False),
    sa.Column('qualification_type', sa.String(length=20), nullable=False),
    sa.Column('canonical_name', sa.String(length=255), nullable=False),
    sa.Column('original_text', sa.Text(), nullable=False),
    sa.Column('evidence_section', sa.String(length=20), nullable=False),
    sa.Column('evidence_strength', sa.Numeric(precision=6, scale=3, asdecimal=False), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=6, scale=3, asdecimal=False), nullable=False),
    sa.CheckConstraint("qualification_type IN ('skill', 'education', 'certification', 'license')", name='ck_candidate_qualifications_type'),
    sa.CheckConstraint('confidence BETWEEN 0 AND 1', name='ck_candidate_qualifications_confidence'),
    sa.CheckConstraint('evidence_strength BETWEEN 0 AND 1', name='ck_candidate_qualifications_strength'),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_qualifications_candidate_id'), 'candidate_qualifications', ['candidate_id'], unique=False)
    op.create_table('employment_records',
    sa.Column('id', db.base.GUID(), nullable=False),
    sa.Column('candidate_id', db.base.GUID(), nullable=False),
    sa.Column('normalized_title', sa.String(length=255), nullable=True),
    sa.Column('original_title', sa.String(length=255), nullable=True),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('date_confidence', sa.Numeric(precision=6, scale=3, asdecimal=False), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employment_records_candidate_id'), 'employment_records', ['candidate_id'], unique=False)
    op.create_table('job_requirements',
    sa.Column('id', db.base.GUID(), nullable=False),
    sa.Column('job_id', db.base.GUID(), nullable=False),
    sa.Column('requirement_type', sa.String(length=20), nullable=False),
    sa.Column('canonical_name', sa.String(length=255), nullable=False),
    sa.Column('original_text', sa.Text(), nullable=False),
    sa.Column('importance', sa.SmallInteger(), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=6, scale=3, asdecimal=False), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('allows_equivalent_experience', sa.Boolean(), nullable=False),
    sa.Column('equivalent_years', sa.Numeric(precision=6, scale=2, asdecimal=False), nullable=True),
    sa.Column('degree_level', sa.String(length=50), nullable=True),
    sa.Column('field_of_study', sa.String(length=255), nullable=True),
    sa.CheckConstraint("requirement_type IN ('skill', 'education', 'certification', 'license')", name='ck_job_requirements_type'),
    sa.CheckConstraint('confidence BETWEEN 0 AND 1', name='ck_job_requirements_confidence'),
    sa.CheckConstraint('importance BETWEEN 1 AND 3', name='ck_job_requirements_importance'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_requirements_job_id'), 'job_requirements', ['job_id'], unique=False)
    op.create_table('job_responsibilities',
    sa.Column('id', db.base.GUID(), nullable=False),
    sa.Column('job_id', db.base.GUID(), nullable=False),
    sa.Column('original_text', sa.Text(), nullable=False),
    sa.Column('normalized_text', sa.Text(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_responsibilities_job_id'), 'job_responsibilities', ['job_id'], unique=False)
    op.create_table('resumes',
    sa.Column('id', db.base.GUID(), nullable=False),
    sa.Column('candidate_id', db.base.GUID(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('parsed_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('parser_version', sa.String(length=50), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resumes_candidate_id'), 'resumes', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_resumes_file_hash'), 'resumes', ['file_hash'], unique=True)
    op.create_table('scoring_runs',
    sa.Column('id', db.base.GUID(), nullable=False),
    sa.Column('job_id', db.base.GUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('scoring_version', sa.String(length=50), nullable=False),
    sa.Column('parser_version', sa.String(length=50), nullable=False),
    sa.Column('taxonomy_version', sa.String(length=50), nullable=False),
    sa.Column('config_snapshot', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('candidate_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status IN ('active', 'invalidated')", name='ck_scoring_runs_status'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scoring_runs_job_id'), 'scoring_runs', ['job_id'], unique=False)
    op.create_table('evidence_bullets',
    sa.Column('id', db.base.GUID(), nullable=False),
    sa.Column('candidate_id', db.base.GUID(), nullable=False),
    sa.Column('employment_id', db.base.GUID(), nullable=True),
    sa.Column('section_type', sa.String(length=20), nullable=False),
    sa.Column('original_text', sa.Text(), nullable=False),
    sa.Column('normalized_text', sa.Text(), nullable=False),
    sa.CheckConstraint("section_type IN ('employment', 'project', 'research')", name='ck_evidence_bullets_section_type'),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['employment_id'], ['employment_records.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_bullets_candidate_id'), 'evidence_bullets', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_evidence_bullets_employment_id'), 'evidence_bullets', ['employment_id'], unique=False)
    op.create_table('match_results',
    sa.Column('id', db.base.GUID(), nullable=False),
    sa.Column('run_id', db.base.GUID(), nullable=False),
    sa.Column('job_id', db.base.GUID(), nullable=False),
    sa.Column('candidate_id', db.base.GUID(), nullable=False),
    sa.Column('required_score', sa.Numeric(precision=6, scale=2, asdecimal=False), nullable=True),
    sa.Column('experience_score', sa.Numeric(precision=6, scale=2, asdecimal=False), nullable=True),
    sa.Column('responsibility_score', sa.Numeric(precision=6, scale=2, asdecimal=False), nullable=True),
    sa.Column('preferred_score', sa.Numeric(precision=6, scale=2, asdecimal=False), nullable=True),
    sa.Column('applied_weights', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('final_score', sa.Numeric(precision=6, scale=2, asdecimal=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['scoring_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'candidate_id', name='uq_match_results_run_candidate')
    )
    op.create_index(op.f('ix_match_results_candidate_id'), 'match_results', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_match_results_run_id'), 'match_results', ['run_id'], unique=False)
    op.create_table('match_evidence',
    sa.Column('id', db.base.GUID(), nullable=False),
    sa.Column('match_result_id', db.base.GUID(), nullable=False),
    sa.Column('requirement_id', db.base.GUID(), nullable=True),
    sa.Column('responsibility_id', db.base.GUID(), nullable=True),
    sa.Column('matched_canonical', sa.String(length=255), nullable=False),
    sa.Column('evidence_text', sa.Text(), nullable=False),
    sa.Column('evidence_section', sa.String(length=20), nullable=False),
    sa.Column('raw_strength', sa.Numeric(precision=6, scale=3, asdecimal=False), nullable=False),
    sa.Column('adjusted_strength', sa.Numeric(precision=6, scale=3, asdecimal=False), nullable=False),
    sa.ForeignKeyConstraint(['match_result_id'], ['match_results.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requirement_id'], ['job_requirements.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['responsibility_id'], ['job_responsibilities.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_match_evidence_match_result_id'), 'match_evidence', ['match_result_id'], unique=False)
    op.create_table('missing_items',
    sa.Column('id', db.base.GUID(), nullable=False),
    sa.Column('match_result_id', db.base.GUID(), nullable=False),
    sa.Column('requirement_id', db.base.GUID(), nullable=False),
    sa.Column('canonical_name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.CheckConstraint("status IN ('not_identified', 'unclear', 'pending_credential')", name='ck_missing_items_status'),
    sa.ForeignKeyConstraint(['match_result_id'], ['match_results.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requirement_id'], ['job_requirements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_missing_items_match_result_id'), 'missing_items', ['match_result_id'], unique=False)
    op.create_table('scoring_warnings',
    sa.Column('id', db.base.GUID(), nullable=False),
    sa.Column('match_result_id', db.base.GUID(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('related_requirement_id', db.base.GUID(), nullable=True),
    sa.ForeignKeyConstraint(['match_result_id'], ['match_results.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['related_requirement_id'], ['job_requirements.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scoring_warnings_match_result_id'), 'scoring_warnings', ['match_result_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scoring_warnings_match_result_id'), table_name='scoring_warnings')
    op.drop_table('scoring_warnings')
    op.drop_index(op.f('ix_missing_items_match_result_id'), table_name='missing_items')
    op.drop_table('missing_items')
    op.drop_index(op.f('ix_match_evidence_match_result_id'), table_name='match_evidence')
    op.drop_table('match_evidence')
    op.drop_index(op.f('ix_match_results_run_id'), table_name='match_results')
    op.drop_index(op.f('ix_match_results_candidate_id'), table_name='match_results')
    op.drop_table('match_results')
    op.drop_index(op.f('ix_evidence_bullets_employment_id'), table_name='evidence_bullets')
    op.drop_index(op.f('ix_evidence_bullets_candidate_id'), table_name='evidence_bullets')
    op.drop_table('evidence_bullets')
    op.drop_index(op.f('ix_scoring_runs_job_id'), table_name='scoring_runs')
    op.drop_table('scoring_runs')
    op.drop_index(op.f('ix_resumes_file_hash'), table_name='resumes')
    op.drop_index(op.f('ix_resumes_candidate_id'), table_name='resumes')
    op.drop_table('resumes')
    op.drop_index(op.f('ix_job_responsibilities_job_id'), table_name='job_responsibilities')
    op.drop_table('job_responsibilities')
    op.drop_index(op.f('ix_job_requirements_job_id'), table_name='job_requirements')
    op.drop_table('job_requirements')
    op.drop_index(op.f('ix_employment_records_candidate_id'), table_name='employment_records')
    op.drop_table('employment_records')
    op.drop_index(op.f('ix_candidate_qualifications_candidate_id'), table_name='candidate_qualifications')
    op.drop_table('candidate_qualifications')
    op.drop_table('jobs')
    op.drop_table('candidates')
    # ### end Alembic commands ###
